### ISSUE TITLE
Rubocop is mad about old configurations and makes Standard not run?

### ISSUE THREAD

**Issue by artfuldodger** [testdouble/standard#167]
I've tried the most recent version of Rubocop and 0.80.1, but both yell a lot about obsolete configurations and then `bundle exec standardrb` exits without doing anything. What can I do?

```
➜  special_sauce git:(standardrb) ✗ bundle exec standardrb --fix
/Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/standard-0.0.36/config/base.yml: Performance/RedundantSortBy has the wrong namespace - should be Style
/Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/standard-0.0.36/config/base.yml: Performance/Sample has the wrong namespace - should be Style
/Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/standard-0.0.36/config/base.yml: Rails/SafeNavigation has the wrong namespace - should be Style
bundler: failed to load command: standardrb (/Users/jon/.rbenv/versions/2.6.5/bin/standardrb)
RuboCop::ValidationError: The `Layout/AlignArray` cop has been renamed to `Layout/ArrayAlignment`.
(obsolete configuration found in /Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/standard-0.0.36/config/base.yml, please update it)
The `Layout/AlignHash` cop has been renamed to `Layout/HashAlignment`.
(obsolete configuration found in /Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/standard-0.0.36/config/base.yml, please update it)
The `Layout/AlignParameters` cop has been renamed to `Layout/ParameterAlignment`.
(obsolete configuration found in /Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/standard-0.0.36/config/base.yml, please update it)
The `Layout/IndentArray` cop has been renamed to `Layout/FirstArrayElementIndentation`.
(obsolete configuration found in /Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/standard-0.0.36/config/base.yml, please update it)
The `Layout/IndentAssignment` cop has been renamed to `Layout/AssignmentIndentation`.
(obsolete configuration found in /Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/standard-0.0.36/config/base.yml, please update it)
The `Layout/IndentHash` cop has been renamed to `Layout/FirstHashElementIndentation`.
(obsolete configuration found in /Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/standard-0.0.36/config/base.yml, please update it)
The `Layout/IndentHeredoc` cop has been renamed to `Layout/HeredocIndentation`.
(obsolete configuration found in /Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/standard-0.0.36/config/base.yml, please update it)
The `Layout/LeadingBlankLines` cop has been renamed to `Layout/LeadingEmptyLines`.
(obsolete configuration found in /Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/standard-0.0.36/config/base.yml, please update it)
The `Layout/TrailingBlankLines` cop has been renamed to `Layout/TrailingEmptyLines`.
(obsolete configuration found in /Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/standard-0.0.36/config/base.yml, please update it)
The `Lint/DuplicatedKey` cop has been renamed to `Lint/DuplicateHashKey`.
(obsolete configuration found in /Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/standard-0.0.36/config/base.yml, please update it)
The `Lint/MultipleCompare` cop has been renamed to `Lint/MultipleComparison`.
(obsolete configuration found in /Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/standard-0.0.36/config/base.yml, please update it)
The `Lint/StringConversionInInterpolation` cop has been renamed to `Lint/RedundantStringCoercion`.
(obsolete configuration found in /Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/standard-0.0.36/config/base.yml, please update it)
The `Lint/UnneededRequireStatement` cop has been renamed to `Lint/RedundantRequireStatement`.
(obsolete configuration found in /Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/standard-0.0.36/config/base.yml, please update it)
The `Lint/UnneededSplatExpansion` cop has been renamed to `Lint/RedundantSplatExpansion`.
(obsolete configuration found in /Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/standard-0.0.36/config/base.yml, please update it)
The `Naming/UncommunicativeBlockParamName` cop has been renamed to `Naming/BlockParameterName`.
(obsolete configuration found in /Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/standard-0.0.36/config/base.yml, please update it)
The `Style/UnneededCapitalW` cop has been renamed to `Style/RedundantCapitalW`.
(obsolete configuration found in /Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/standard-0.0.36/config/base.yml, please update it)
The `Style/UnneededCondition` cop has been renamed to `Style/RedundantCondition`.
(obsolete configuration found in /Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/standard-0.0.36/config/base.yml, please update it)
The `Style/UnneededInterpolation` cop has been renamed to `Style/RedundantInterpolation`.
(obsolete configuration found in /Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/standard-0.0.36/config/base.yml, please update it)
The `Style/UnneededPercentQ` cop has been renamed to `Style/RedundantPercentQ`.
(obsolete configuration found in /Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/standard-0.0.36/config/base.yml, please update it)
  /Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-0.80.1/lib/rubocop/config_obsoletion.rb:219:in `reject_obsolete_cops_and_parameters'
  /Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-0.80.1/lib/rubocop/config_validator.rb:36:in `validate'
  /Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-0.80.1/lib/rubocop/config.rb:44:in `check'
  /Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-0.80.1/lib/rubocop/config.rb:37:in `create'
  /Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-0.80.1/lib/rubocop/config_loader.rb:54:in `load_file'
  /Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-0.80.1/lib/rubocop/config_store.rb:23:in `options_config='
  /Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/standard-0.0.36/lib/standard/creates_config_store/assigns_rubocop_yaml.rb:6:in `call'
  /Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/standard-0.0.36/lib/standard/creates_config_store.rb:17:in `block in call'
  /Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/standard-0.0.36/lib/standard/creates_config_store.rb:16:in `tap'
  /Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/standard-0.0.36/lib/standard/creates_config_store.rb:16:in `call'
  /Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/standard-0.0.36/lib/standard/builds_config.rb:22:in `call'
  /Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/standard-0.0.36/lib/standard/cli.rb:16:in `run'
  /Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/standard-0.0.36/exe/standardrb:7:in `<top (required)>'
  /Users/jon/.rbenv/versions/2.6.5/bin/standardrb:23:in `load'
  /Users/jon/.rbenv/versions/2.6.5/bin/standardrb:23:in `<top (required)>
```

**Comment by searls** [comment]
I think this version of standard is quite old and at the time was not pegged to a certain version of Rubocop. The current version (0.2.3) more carefully pegs to minor releases of rubocop (including 0.80.1) and has been updated for changes to cops

**Comment by artfuldodger** [comment]
That's embarrassing - not sure how I ended up on such an old version. Sorry and thanks!

**Comment by searls** [comment]
No worries—have a great day!

**Comment by richardkmiller** [comment]
@searls FYI, I also ran into this today on a project that's already using Rubocop. I added `gem "standard", group: [:development, :test]` to the Gemfile and ran `bundle` and standard 0.0.36 was bundled.

Then I reverted these edits (`git checkout .`) then *replaced* `gem "rubocop"` with `gem "standard"`, ran `bundle`, and it bundled standard 1.0.5.

**Comment by seanfcarroll** [comment]
I had the same problem and the same fix worked.

**Comment by twe4ked** [comment]
Maybe a 0.0.37 release with a post-install warning could help with this popping up.
